export const GAME = {
	CREATE_CLONES: "CREATE_CLONES",
	DELETE_CLONES: "DELETE_CLONES",
	SERUM_CLONES: "SERUM_CLONES"
};

export const TOOLS = {
	CREATE_CRONJOB: "CREATE_CRONJOB",
	DELETE_CRONJOB: "DELETE_CRONJOB"
};

export const AGED_CLONES = {
	CREATE_CHILD_CLONE: "CREATE_CHILD_CLONE",
	CREATE_TEEN_CLONE: "CREATE_TEEN_CLONE",
	CREATE_ADULT_CLONE: "CREATE_ADULT_CLONE",
	CREATE_SENIOR_CLONE: "CREATE_SENIOR_CLONE",
	CREATE_ANCIENT_CLONE: "CREATE_ANCIENT_CLONE",
	SERUM_CHILD_CLONE: "SERUM_CHILD_CLONE",
	SERUM_TEEN_CLONE: "SERUM_TEEN_CLONE",
	SERUM_ADULT_CLONE: "SERUM_ADULT_CLONE",
	SERUM_SENIOR_CLONE: "SERUM_SENIOR_CLONE",
	SERUM_ANCIENT_CLONE: "SERUM_ANCIENT_CLONE"
};
