export const GAME = {
	CLONES: {
		UPDATE: "UPDATE_CLONES",
		UPDATE_CPS: "UPDATE_CLONES_PER_SECOND",
	},
	MONEY: {
		EARN: "EARN_MONEY",
		SPEND: "SPEND_MONEY",
	},
	AGING_SERUM: {
		EARN: "EARN_AGING_SERUM",
		SPEND: "SPEND_AGING_SERUM",
	},
	ANGER_SERUM: {
		EARN: "EARN_ANGER_SERUM",
		SPEND: "SPEND_ANGER_SERUM",
	},
	CHAOS_SERUM: {
		EARN: "EARN_CHAOS_SERUM",
		SPEND: "SPEND_CHAOS_SERUM",
	},
};

export const TIME = {
	TOTAL: {
		UPDATE: "UPDATE_TOTAL",
		CLEAR: "CLEAR_TOTAL",
	},
	SEC: {
		UPDATE: "UPDATE_SEC",
		CLEAR: "CLEAR_SEC",
	},
	DEC: {
		UPDATE: "UPDATE_DEC",
		CLEAR: "CLEAR_DEC",
	}
};

export const TOOLS = {
	AUTO_CLONE: {
		UNLOCK: "UNLOCK_AUTO_CLONE",
		CREATE: "CREATE_AUTO_CLONE",
		DELETE: "DELETE_AUTO_CLONE",
	},
	AUTO_SELL: {
		UNLOCK: "UNLOCK_AUTO_SELL",
		CREATE: "CREATE_AUTO_SELL",
		DELETE: "DELETE_AUTO_SELL",
	},
	AUTO_SERUM: {
		UNLOCK: "UNLOCK_AUTO_SERUM",
		CREATE: "CREATE_AUTO_SERUM",
		DELETE: "DELETE_AUTO_SERUM",
	},
};

export const CLONES = {
	FETUS: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_FETUS",
			SELL: "UNLOCK_SELL_FETUS",
			SERUM: "UNLOCK_SELL_FETUS",
		},
		CREATE: "CREATE_CLONE_FETUS",
		KILL: "KILL_CLONE_FETUS",
		SELL: "SELL_CLONE_FETUS",
		SERUM: "SERUM_CLONE_FETUS",
	},
	CHILD: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_CHILD",
			SELL: "UNLOCK_SELL_CHILD",
			SERUM: "UNLOCK_SELL_CHILD",
		},
		CREATE: "CREATE_CLONE_CHILD",
		KILL: "KILL_CLONE_CHILD",
		SELL: "SELL_CLONE_CHILD",
		SERUM: "SERUM_CLONE_CHILD",
	},
	TEEN: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_TEEN",
			SELL: "UNLOCK_SELL_TEEN",
			SERUM: "UNLOCK_SELL_TEEN",
		},
		CREATE: "CREATE_CLONE_TEEN",
		KILL: "KILL_CLONE_TEEN",
		SELL: "SELL_CLONE_TEEN",
		SERUM: "SERUM_CLONE_TEEN",
	},
	ADULT: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_ADULT",
			SELL: "UNLOCK_SELL_ADULT",
			SERUM: "UNLOCK_SELL_ADULT",
		},
		CREATE: "CREATE_CLONE_ADULT",
		KILL: "KILL_CLONE_ADULT",
		SELL: "SELL_CLONE_ADULT",
		SERUM: "SERUM_CLONE_ADULT",
	},
	SENIOR: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_SENIOR",
			SELL: "UNLOCK_SELL_SENIOR",
			SERUM: "UNLOCK_SELL_SENIOR",
		},
		CREATE: "CREATE_CLONE_SENIOR",
		KILL: "KILL_CLONE_SENIOR",
		SELL: "SELL_CLONE_SENIOR",
		SERUM: "SERUM_CLONE_SENIOR",
	},
	ANCIENT: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_ANCIENT",
			SELL: "UNLOCK_SELL_ANCIENT",
			SERUM: "UNLOCK_SELL_ANCIENT",
		},
		CREATE: "CREATE_CLONE_ANCIENT",
		KILL: "KILL_CLONE_ANCIENT",
		SELL: "SELL_CLONE_ANCIENT",
		SERUM: "SERUM_CLONE_ANCIENT",
	},
};

export const STATS = {
	TIME: {
		ADD_IN_TOTAL: "ADD_TIME_IN_TOTAL"
	},
	OUTBREAKS: {
		ADD_IN_TOTAL: "ADD_OUTBREAKS_IN_TOTAL"
	},
	CLONES: {
		ADD_BY_CLICK: "ADD_CLONES_BY_CLICK",
		ADD_IN_TOTAL: "ADD_CLONES_IN_TOTAL",
		ADD_KILLED: "ADD_KILLED_CLONES",
		ADD_SOLD: "ADD_SOLD_CLONES",
	},
	MONEY: {
		ADD_IN_TOTAL: "ADD_MONEY_IN_TOTAL",
		ADD_SPEND: "ADD_SPEND_MONEY",
	},
	AGING_SERUM: {
		ADD_IN_TOTAL: "ADD_AGING_SERUM_IN_TOTAL",
		ADD_SPEND: "ADD_SPEND_AGING_SERUM",
	},
	ANGER_SERUM: {
		ADD_IN_TOTAL: "ADD_ANGER_SERUM_IN_TOTAL",
		ADD_SPEND: "ADD_SPEND_ANGER_SERUM",
	},
	CHAOS_SERUM: {
		ADD_IN_TOTAL: "ADD_CHAOS_SERUM_IN_TOTAL",
		ADD_SPEND: "ADD_SPEND_CHAOS_SERUM",
	},
};

export const UI = {
	MENU: {
		OPEN: "OPEN_MENU",
		CLOSE: "CLOSE_MENU",
		TOGGLE: "TOGGLE_MENU",
		SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_MENU",
		CLEAR_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_MENU",
	},
	TABS: {
		CLONES: {
			SELECT: "SELECT_CLONES_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_CLONES_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_CLONES_TAB",
		},
		TOOLS: {
			SELECT: "SELECT_TOOLS_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_TOOLS_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_TOOLS_TAB",
		},
		UPGRADES: {
			SELECT: "SELECT_UPGRADES_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_UPGRADES_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_UPGRADES_TAB",
		},
		ACHIEVEMENTS: {
			SELECT: "SELECT_ACHIEVEMENTS_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_ACHIEVEMENTS_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_ACHIEVEMENTS_TAB",
		},
		STATS: {
			SELECT: "SELECT_STATS_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_STATS_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_STATS_TAB",
		},
		CONFIG: {
			SELECT: "SELECT_CONFIG_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_CONFIG_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_CONFIG_TAB",
		},
		CREDITS: {
			SELECT: "SELECT_CREDITS_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_CREDITS_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_CREDITS_TAB",
		}
	}
};