export const GAME = {
	CREATE_CLONES: "CREATE_CLONES",
	DELETE_CLONES: "DELETE_CLONES",
	SERUM_CLONES: "SERUM_CLONES",
	UPDATE_CLONES: "UPDATE_CLONES",
	UPDATE_CPS: "UPDATE_CLONES_PER_SECOND",
};

export const TIME = {
	UPDATE_TOTAL: "UPDATE_TOTAL",
	UPDATE_SEC: "UPDATE_SEC",
	UPDATE_DEC: "UPDATE_DEC",
	CLEAR_SEC: "CLEAR_SEC",
	CLEAR_DEC: "CLEAR_DEC",
};

export const TOOLS = {
	CREATE_AUTO_CLONE: "CREATE_AUTO_CLONE",
	CREATE_AUTO_SERUM: "CREATE_AUTO_SERUM",
	DELETE_AUTO_CLONE: "DELETE_AUTO_CLONE",
	DELETE_AUTO_SERUM: "DELETE_AUTO_SERUM",
};

export const AGED_CLONES = {
	CREATE_CHILD_CLONE: "CREATE_CHILD_CLONE",
	CREATE_TEEN_CLONE: "CREATE_TEEN_CLONE",
	CREATE_ADULT_CLONE: "CREATE_ADULT_CLONE",
	CREATE_SENIOR_CLONE: "CREATE_SENIOR_CLONE",
	CREATE_ANCIENT_CLONE: "CREATE_ANCIENT_CLONE",
	SERUM_CHILD_CLONE: "SERUM_CHILD_CLONE",
	SERUM_TEEN_CLONE: "SERUM_TEEN_CLONE",
	SERUM_ADULT_CLONE: "SERUM_ADULT_CLONE",
	SERUM_SENIOR_CLONE: "SERUM_SENIOR_CLONE",
	SERUM_ANCIENT_CLONE: "SERUM_ANCIENT_CLONE",
};
