export const STATS = {
	TIME: {
		ADD_IN_TOTAL: "ADD_TIME_IN_TOTAL"
	},
	OUTBREAKS: {
		ADD_IN_TOTAL: "ADD_OUTBREAKS_IN_TOTAL"
	},
	CLONES: {
		ADD_BY_CLICK: "ADD_CLONES_BY_CLICK",
		ADD_IN_TOTAL: "ADD_CLONES_IN_TOTAL",
		ADD_KILLED: "ADD_KILLED_CLONES",
		ADD_SOLD: "ADD_SOLD_CLONES",
	},
	MONEY: {
		ADD_IN_TOTAL: "ADD_MONEY_IN_TOTAL",
		ADD_SPEND: "ADD_SPEND_MONEY",
	},
	AGING_SERUM: {
		ADD_IN_TOTAL: "ADD_AGING_SERUM_IN_TOTAL",
		ADD_SPEND: "ADD_SPEND_AGING_SERUM",
	},
	ANGER_SERUM: {
		ADD_IN_TOTAL: "ADD_ANGER_SERUM_IN_TOTAL",
		ADD_SPEND: "ADD_SPEND_ANGER_SERUM",
	},
	CHAOS_SERUM: {
		ADD_IN_TOTAL: "ADD_CHAOS_SERUM_IN_TOTAL",
		ADD_SPEND: "ADD_SPEND_CHAOS_SERUM",
	},
};
