export const UI = {
	MENU: {
		OPEN: "OPEN_MENU",
		CLOSE: "CLOSE_MENU",
		TOGGLE: "TOGGLE_MENU",
		SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_MENU",
		CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_MENU",
	},
	TABS: {
		CLONES: {
			SELECT: "SELECT_CLONES_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_CLONES_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_CLONES_TAB",
		},
		TOOLS: {
			SELECT: "SELECT_TOOLS_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_TOOLS_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_TOOLS_TAB",
		},
		UPGRADES: {
			SELECT: "SELECT_UPGRADES_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_UPGRADES_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_UPGRADES_TAB",
		},
		ACHIEVEMENTS: {
			SELECT: "SELECT_ACHIEVEMENTS_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_ACHIEVEMENTS_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_ACHIEVEMENTS_TAB",
		},
		STATS: {
			SELECT: "SELECT_STATS_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_STATS_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_STATS_TAB",
		},
		CONFIG: {
			SELECT: "SELECT_CONFIG_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_CONFIG_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_CONFIG_TAB",
		},
		CREDITS: {
			SELECT: "SELECT_CREDITS_TAB",
			SET_NOTIFICATIONS: "SET_NOTIFICATIONS_IN_CREDITS_TAB",
			CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS_IN_CREDITS_TAB",
		}
	}
};