export const TOOLS = {
	AUTO_CLONE: {
		UNLOCK: "UNLOCK_AUTO_CLONE",
		CREATE: "CREATE_AUTO_CLONE",
		DELETE: "DELETE_AUTO_CLONE",
	},
	AUTO_SELL: {
		UNLOCK: "UNLOCK_AUTO_SELL",
		CREATE: "CREATE_AUTO_SELL",
		DELETE: "DELETE_AUTO_SELL",
	},
	AUTO_SERUM: {
		UNLOCK: "UNLOCK_AUTO_SERUM",
		CREATE: "CREATE_AUTO_SERUM",
		DELETE: "DELETE_AUTO_SERUM",
	},
};
