export const GAME = {
	CLONES: {
		UPDATE: "UPDATE_CLONES",
		UPDATE_CPS: "UPDATE_CLONES_PER_SECOND",
	},
	MONEY: {
		EARN: "EARN_MONEY",
		SPEND: "SPEND_MONEY",
	},
	AGING_SERUM: {
		EARN: "EARN_AGING_SERUM",
		SPEND: "SPEND_AGING_SERUM",
	},
	ANGER_SERUM: {
		EARN: "EARN_ANGER_SERUM",
		SPEND: "SPEND_ANGER_SERUM",
	},
	CHAOS_SERUM: {
		EARN: "EARN_CHAOS_SERUM",
		SPEND: "SPEND_CHAOS_SERUM",
	},
};