export const GAME = {
	ENERGY: {
		GENERATE: "GENERATE_ENERGY",
		USE: "USE_ENERGY",
		FREE: "FREE_ENERGY",
	},
	ROOM: {
		BUY: "BUY_ROOM",
		USE: "USE_ROOM",
		FREE: "FREE_ROOM",
	},
	CLONES: {
		UPDATE: "UPDATE_CLONES",
		UPDATE_CPS: "UPDATE_CLONES_PER_SECOND",
	},
};