export const ANIMATIONS = {
	ASSISTANT: {
		SET_FACE_EXPRESSION: "SET_FACE_EXPRESSION",
		SET_BODY_EXPRESSION: "SET_BODY_EXPRESSION",
		SET_EYE_DIRECTION: "SET_EYE_DIRECTION",
		SET_TALKING: "SET_TALKING",
	}
};
