export const ANIMATIONS = {
	ASSISTANT: {
		SET_FACE: "SET_FACE",
		SET_BODY: "SET_BODY",
		SET_EYE_DIRECTION: "SET_EYE_DIRECTION",
		SET_TALKING: "SET_TALKING",
	},
	CLONES: {
		NONE: "SET_NONE",
		FETUS: {
			CREATION: "SET_FETUS_CREATION",
			LOOP: "SET_FETUS_LOOP",
		}
	}
};
