export const CLONES = {
	FETUS: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_FETUS",
			SELL: "UNLOCK_SELL_FETUS",
			SERUM: "UNLOCK_SELL_FETUS",
		},
		CREATE: "CREATE_CLONE_FETUS",
		KILL: "KILL_CLONE_FETUS",
		SELL: "SELL_CLONE_FETUS",
		SERUM: "SERUM_CLONE_FETUS",
	},
	CHILD: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_CHILD",
			SELL: "UNLOCK_SELL_CHILD",
			SERUM: "UNLOCK_SELL_CHILD",
		},
		CREATE: "CREATE_CLONE_CHILD",
		KILL: "KILL_CLONE_CHILD",
		SELL: "SELL_CLONE_CHILD",
		SERUM: "SERUM_CLONE_CHILD",
	},
	TEEN: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_TEEN",
			SELL: "UNLOCK_SELL_TEEN",
			SERUM: "UNLOCK_SELL_TEEN",
		},
		CREATE: "CREATE_CLONE_TEEN",
		KILL: "KILL_CLONE_TEEN",
		SELL: "SELL_CLONE_TEEN",
		SERUM: "SERUM_CLONE_TEEN",
	},
	ADULT: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_ADULT",
			SELL: "UNLOCK_SELL_ADULT",
			SERUM: "UNLOCK_SELL_ADULT",
		},
		CREATE: "CREATE_CLONE_ADULT",
		KILL: "KILL_CLONE_ADULT",
		SELL: "SELL_CLONE_ADULT",
		SERUM: "SERUM_CLONE_ADULT",
	},
	SENIOR: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_SENIOR",
			SELL: "UNLOCK_SELL_SENIOR",
			SERUM: "UNLOCK_SELL_SENIOR",
		},
		CREATE: "CREATE_CLONE_SENIOR",
		KILL: "KILL_CLONE_SENIOR",
		SELL: "SELL_CLONE_SENIOR",
		SERUM: "SERUM_CLONE_SENIOR",
	},
	ANCIENT: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_ANCIENT",
			SELL: "UNLOCK_SELL_ANCIENT",
			SERUM: "UNLOCK_SELL_ANCIENT",
		},
		CREATE: "CREATE_CLONE_ANCIENT",
		KILL: "KILL_CLONE_ANCIENT",
		SELL: "SELL_CLONE_ANCIENT",
		SERUM: "SERUM_CLONE_ANCIENT",
	},
};
