export const CLONES = {
	FETUS: {
		UNLOCK: {
			CLONE: "UNLOCK_CLONE_FETUS",
			SELL: "UNLOCK_SELL_FETUS",
			SERUM: "UNLOCK_SELL_FETUS",
		},
		CREATE: "CREATE_CLONE_FETUS",
		KILL: "KILL_CLONE_FETUS",
		SELL: "SELL_CLONE_FETUS",
		SERUM: "SERUM_CLONE_FETUS",
	}
};
